apiVersion: apps/v1
kind: Deployment
metadata:
  name:wscd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wscd
  template:
    metadata:
      labels:
        app: wscd
    spec:
      containers:
      - image: okteto.dev/wscd:latest
        name:wscd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f558f164-08a0-11ed-861d-0242ac120002"
        - name: Vless_Path
          value: "/vl953"
        - name: Vmess_UUID
          value: "f558f164-08a0-11ed-861d-0242ac120002"
        - name: Vmess_Path
          value: "/vm742"
        - name: Share_Path
          value: "/v2link"
